version: "3"

# NETWORK
networks:
  my-networks:
    driver: bridge

# VOLUME
volumes:
  dir-site:
    driver_opts:
      device: E:\CodeProjects\theory_note\docker\docker\volume
      o: bind
      type: none
  
# CONTAINERs = services
services:
  # CONTAINER PHP
  my-php:
    container_name: php-product
    build:
      dockerfile: Dockerfile
      context: ./php/
    hostname: php
    restart: always
    networks:
      - my-networks
    volumes:
      - dir-site:/home/sites/
  # CONTAINER HTTPD
  my-httpd:
    container_name: httpd-product
    image: "httpd:latest"
    hostname: httpd
    restart: always
    networks:
      - my-networks
    volumes:
      - dir-site:/home/sites/
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "8000:80"
      - "443:443"
  # CONTAINER MYSQL
  my-mysql:
    container_name: mysql-product
    image: "mysql:latest"
    hostname: mysql
    restart: always
    networks:
      - my-networks
    volumes:
      - dir-site:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123abc
      - MYSQL_DATABASE=db_site
      - MYSQL_USER=siteuser
      - MYSQL_PASSWORD=sitepass
